# Generated by Django 5.2.7 on 2025-12-13 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forno_italiano_app', '0002_booking_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
    ]
